# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_event', models.IntegerField(blank=True)),
                ('message', models.CharField(blank=True, max_length=250)),
                ('clock_virt_seed', models.DateTimeField()),
                ('clock_virt_rate', models.FloatField()),
                ('clock_real_seed', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StateChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False)),
                ('event_number', models.IntegerField(blank=True)),
                ('virtual_clock', models.DateTimeField(blank=True, null=True)),
                ('clock_speed', models.FloatField()),
            ],
        ),
    ]
